apiVersion: v1
kind: Pod
metadata:
  name: tcpdump-debug
  namespace: istio-telemetry  # Optional
spec:
  nodeSelector:
    kubernetes.io/hostname:  k8s-node2 # Replace with actual node name
  containers:
  - name: tcpdump
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]

